
title: AliLynne
author: Ali Thompson
email: alilynne.thompson@gmail.com
headshot: assets/me.jpg
description: > # this means to ignore newlines until "twitter_username:"
  I have a passion for creating websites that are accessible to all. 
# social links
twitter_username: alilynnet
github_username:  alilynne
rss: rss
dribbble_username: jekyll
facebook_username: jekyll
flickr_username: jekyll
instagram_username: jekyll
linkedin_username: jekyll
pinterest_username: jekyll
youtube_username: jekyll
googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # set to true to show excerpts on the homepage

# Bright date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
bright:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

plugins:
 - jekyll-feed

livereload: true

sass:
  sass_dir: _sass

permalink: /:year/:month/:day/:title 